# -*- coding: utf-8 -*-
CANDIDATES_URL = "https://www.marincounty.gov/departments/elections/november-3-2026-general-election/information-and-about-candidates-110326/local-candidates-ballot-110326"

RACES = [
    ("Marin County Board of Education Board of Education Member, Trustee Area 3", "", [
        ("Irish, Cynthia Johanson", "Appointed Incumbent"),
        ("Adams, Craig Stuart", "Realtor / Author"),
    ]),
    ("Marin County Board of Education Board of Education Member, Trustee Area 5", "", [
        ("Nemzer, Marilyn", "Trustee, Marin County Board Of Education, Trustee Area 5"),
        ("Lieberman, Avery", "Dentist / Inventor / Parent"),
    ]),
    ("Marin County Board of Education Board of Education Member, Trustee Area 6", "", [
        ("Robinson, Curtis F.", "Incumbent"),
        ("Goddard, James", "Chief Financial Officer"),
    ]),
    ("Sonoma County Board of Education Board of Education Member, Trustee Area 2",
     'Cross-county jurisdiction: this is a Sonoma County Board of Education trustee area, not Marin County. Included because it appears on Marin’s official local candidates list (the trustee area likely overlaps Marin) - verify before publishing under "Marin County"', [
        ("Lenz, Jonathan", "Educator"),
        ("Quinn, Caitlin", "Nonprofit Union President"),
    ]),
    ("Petaluma Joint Union High School District Governing Board Member, Trustee Area 3",
     'Cross-county jurisdiction: Petaluma Joint Union HSD is primarily a Sonoma County district. Included because it appears on Marin’s official local candidates list - verify before publishing under "Marin County"', [
        ("Garcia, John", "Physician / Medical Director"),
        ("Holmes, Laura", "Parent / HR Consultant"),
    ]),
    ("Tamalpais Union High School District Governing Board Member", "", [
        ("Roenisch, Cynthia C.", "Incumbent"),
        ("Saavedra, Kevin C.", "Incumbent"),
        ("Sandoval, Maria D.", "Spanish Teacher"),
        ("Scully Koo, Joy", "Community Advocate / Parent"),
        ("Sutherland, Brian A.", "Constitutional Lawyer / Parent"),
        ("Wynn, Valerie", "Retired District Teacher"),
        ("Harlander, Leslie J.", "Retired Civil Engineer"),
    ]),
    ("Miller Creek School District Governing Board Member", "", [
        ("Honsberger, Brad", "Incumbent"),
        ("Hutchinson, Megan Roberts", "Incumbent"),
        ("McShane, Caitlin", "Incumbent"),
        ("Compton, Adam", "Software Engineer / Parent"),
        ("Dance, Matt", "Parent / School Volunteer"),
    ]),
    ("Lagunitas School District Governing Board Member", "", [
        ("Michelson, Aaron", "Incumbent"),
        ("Troy, Charlotte Burger", "Mother"),
        ("Wilson, Ally Dukkers", "Parent"),
        ("Cort, David", "Retired"),
    ]),
    ("Novato Unified School District Governing Board Member, Trustee Area 4", "", [
        ("Picus, Abbey", "Incumbent"),
        ("Drouillard, Francis", "Registered Professional Engineer"),
    ]),
    ("Reed Union School District Governing Board Member", "", [
        ("Ghaffary, Mike", "Appointed Incumbent"),
        ("Tsai, Shelby Pasarell", "Incumbent"),
        ("Antani, Krupa", "Parent / School Volunteer"),
        ("Godfrey, Lina", "Nonprofit Director / Mother"),
    ]),
    ("Ross School District Governing Board Member", "", [
        ("Mozaffarian, Darius", "Governing Board Member, Ross School District"),
        ("Solar, Gabriella 'Gabby'", "Parent / School Volunteer"),
        ("Sutro, Elizabeth 'Beth'", "Parent / School Volunteer"),
        ("Allen-Hughes, David", "School Administrator / Parent"),
        ("Hill, Brad", "Parent / School Volunteer"),
    ]),
    ("Sausalito Marin City School District Governing Board Member", "", [
        ("Walters, Lauren J.", "Trustee, Sausalito Marin City School District"),
        ("Holcomb, Leshawn", "Educator / Nonprofit Director"),
        ("Maunder, Alena", "Registered Nurse"),
        ("Vazquez, Eduardo", "Social Worker / Parent"),
    ]),
    ("City of Belvedere Member City Council", "", [
        ("Mark, Peter", "Incumbent"),
        ("Cooper, Jane", "Incumbent"),
    ]),
    ("Town of Corte Madera Member Town Council", "", [
        ("Beckman, Eli", "Councilmember / Architect"),
        ("Ravasio, Pat", "Incumbent"),
        ("Bell, David C.", "Environmental Engineer"),
        ("Fruin, Ava", "School Board Trustee"),
        ("Gallegos, Deborah E.", "Deputy Controller"),
    ]),
    ("Town of Fairfax Member Town Council", "", [
        ("Bragman, Larry", "Attorney"),
        ("Adams, Susan Denise", "Retired Environmental Attorney"),
        ("Da Cunha, Matt", "Retired Firefighter"),
        ("Harmon, Aubrey", "Therapist / Parent"),
        ("Kelly, Doug", "Director, Ross Valley Sanitary District"),
        ("Scorza, Cheryl", "Nursing Assistant / Mother"),
    ]),
    ("Town of Fairfax Town Clerk", "", [
        ("Benson, Deborah", "Accountant / Management Consultant"),
        ("Ackerman, Bruce", "Engineer"),
    ]),
    ("Town of Fairfax Town Treasurer", "", [
        ("Friedman, Talia", "Appointed Incumbent"),
    ]),
    ("City of Larkspur Member City Council", "", [
        ("Andre, Stephanie", "Incumbent"),
        ("Margulies, Sarah", "Larkspur Councilmember"),
        ("Walter, Gareth", "Nonprofit President / Parent"),
        ("Burnett, Aaron", "Policy Director / Father"),
        ("Doyle, Spencer", "Technology Business Executive"),
        ("Friedel, Jeanne", "Operations Manager"),
        ("Jaffe, Brian H.", "Homebuilder / Energy Consultant"),
    ]),
    ("City of Mill Valley Member City Council", "", [
        ("Burke, Stephen", "Incumbent"),
        ("Perrey, Max", "Mill Valley Councilmember"),
    ]),
    ("City of Novato Councilmember District 2", "", [
        ("Farac, Rachel", "Incumbent"),
        ("Little, Mike", "Distribution Design Engineer"),
        ("Rasmussen, Bob", "Electric Incident Investigator"),
    ]),
    ("City of Novato Councilmember District 4", "", [
        ("Eklund, Pat", "Novato Councilmember"),
        ("Galletto, Luiggino", "Entertainment Development Strategist"),
        ("Carpiniello, Chris", "Homebuilder / Business Owner"),
        ("Christian, Dan", "Pastor / Educator / Commissioner"),
    ]),
    ("Town of Ross Member Town Council", "", [
        ("Herbst, Robert", "Real Estate Executive"),
        ("Kuhn, Jeffrey", "Ross Town Treasurer"),
        ("McMillan, Julie A", "Incumbent"),
        ("Roesler, Paul J.", "Business Executive"),
    ]),
    ("Town of San Anselmo Member Town Council", "", [
        ("Burdo, Steve", "San Anselmo Councilmember"),
        ("Chigos, Philip", "Father / Businessowner"),
        ("Dittmar, Will", "Nonprofit CEO"),
    ]),
    ("Town of San Anselmo Town Clerk", "", [
        ("Wilson, Cecily T.", "Incumbent"),
    ]),
    ("Town of San Anselmo Town Treasurer", "", [
        ("Lopin, Lori J.", "Chief Financial Officer"),
    ]),
    ("City of San Rafael Councilmember District 2", "", [
        ("Hill, Eli", "Incumbent"),
    ]),
    ("City of San Rafael Councilmember District 3", "", [
        ("Davidi, Daryoush", "San Rafael Businessowner"),
        ("Sandoval, Robert", "Planning Commissioner / Attorney"),
    ]),
    ("City of Sausalito Member City Council", "", [
        ("Cox, Joan", "Incumbent"),
        ("Hoffman, Jill James", "Incumbent"),
        ("Saad, Nastassya", "Consultant / Planning Commissioner"),
        ("Brinton, Adrian", "Community Advocate"),
    ]),
    ("Town of Tiburon Member Town Council", "", [
        ("Defever, Kathleen", "Attorney / Business Owner"),
        ("Fredericks, Alice", "Tiburon Town Councilmember"),
        ("Hornbrook, Chuck", "Consultant"),
        ("Ryan, Jack", "Tiburon Town Councilmember"),
        ("Jafar, Faris", "Hedge Fund Founder"),
    ]),
    ("Bel Marin Keys Community Services District Director", "", [
        ("Lattanzio, Vincent P.", "Incumbent"),
        ("Nash, Steven", "Incumbent"),
        ("Dugan, Kevin", ""),
    ]),
    ("Marin City Community Services District Director", "", [
        ("Douglas, Kevin", "Incumbent"),
        ("Haynes, Angela", "Incumbent"),
        ("McKinley, Eboni", ""),
        ("McLemore, Royce", ""),
        ("Morgan, Derek", ""),
        ("Price, Capri M.", "Behavior Technician"),
        ("Wiggins, La Tanya J.", "Childcare Provider / Parent"),
        ("Hall, Beatra", "Marin City Library Assistant"),
    ]),
    ("Marin City Community Services District Director - Short Term", "", [
        ("Canson, Sarah Elizabeth", "Appointed Incumbent"),
        ("Harris Green, Terrie", "CSD Director"),
    ]),
    ("Southern Marin Fire Protection District Director", "", [
        ("Chun, Kurt", "Incumbent"),
        ("Deberry, Cristine Soto", "Incumbent"),
        ("Fleming, Peter", "Incumbent"),
        ("Perazzo, Thomas W.", "Incumbent"),
        ("Steinhofer, Eric", "Energy Consultant"),
        ("Svendberg, Amy", "Small Business Owner"),
        ("Clark, Thomas", "Retired"),
    ]),
    ("Marin Healthcare District Director, Division 1", "", [
        ("Hess, Clayton", "Public Health Physician"),
        ("Hoepper, Kendra", "Administrator / Professor / Nurse"),
    ]),
    ("Marin Healthcare District Director, Division 3", "", [
        ("Su, Brian", "Incumbent"),
        ("Goff, Jonathan", "Orthopedic Surgeon"),
    ]),
    ("Bolinas Community Public Utility District Director", "", [
        ("Alexander Green, Andrew", ""),
        ("Godino, Grace", "Incumbent"),
        ("Murch, Mickey", "Farmstand Farmer"),
        ("Siedman, Nathan", "School Board Trustee"),
    ]),
    ("Strawberry Recreation District Director", "", [
        ("Saghezchi, Sohrab", "Incumbent"),
        ("Teese, Peter", "Incumbent"),
        ("Waterfield, Sarah G.", "Incumbent"),
        ("Morgenthaler, David T.", "Father / Community Advocate"),
    ]),
    ("Strawberry Recreation District Director - Short Term", "", [
        ("Twillman, Doug", "Appointed Incumbent"),
        ("Hawkins, Aliza", "Businesswoman / Mother"),
    ]),
    ("Richardson Bay Sanitary District Director", "", [
        ("Fitzgerald, Mark", "Incumbent"),
        ("McIntosh, Peter", "Incumbent"),
        ("Walravens, Patrick", "Incumbent"),
        ("Turnacliff, John", "Equipment Financing Executive"),
    ]),
    ("North Marin Water District Director, Division 5", "", [
        ("Lewis, Marc Hunter", "Community Policy Advocate"),
        ("Williams, Laurie L.", "Principal Planner"),
    ]),
]

# (letter, jurisdiction, description, source_url, flag)
BASE = "https://www.marincounty.gov/departments/elections/november-3-2026-general-election/information-about-measures-110326/list-measures-110326/"

MEASURES = [
    ("AB", "Sonoma County Junior College District",
     "Without increasing tax rates, to improve facilities to train students for careers in nursing/firefighting/first responders, building trades, agriculture, auto mechanics; attract/retain high quality faculty, prepare students for universities; repair leaky roofs; repair, construct, and acquire classrooms/sites/facilities/equipment, shall the Sonoma County Junior College District measure be adopted authorizing $830,000,000 in bonds at legal rates, levying $25 per $100,000 of assessed valuation ($55,300,000 annually), while bonds are outstanding, and with oversight/audits/local control?",
     BASE + "measure-ab-110326",
     'Cross-county jurisdiction: Sonoma County Junior College District, not Marin County - included because it appears on Marin’s official measures list - verify before publishing under "Marin County"'),
    ("N", "Miller Creek School District",
     "Miller Creek Elementary School District Classroom Repair/ Upgrade Measure. To improve aging local elementary/middle schools by fixing bathrooms, plumbing, roofs, HVAC, and electrical systems; upgrading classrooms to support high quality math, science, technology, reading, writing, arts/music instruction; and improve school security/ student safety, shall Miller Creek Elementary School District’s measure be adopted authorizing $67,000,000 in bonds at legal rates, with levies averaging $28 per $100,000 assessed value ($3,800,000 annually) while bonds are outstanding, independent oversight, audits and all funds locally controlled?",
     BASE + "measure-n-110226", ""),
    ("O", "Reed Union School District",
     "Reed Union School District Repair, Safety, Upgrade Measure: To support quality education and retain/attract quality teachers by upgrading all Reed schools, keeping them safe; repairing deteriorating classrooms/bathrooms, leaky roofs; updating fire/electrical/security systems and earthquake safety; removing mold/asbestos; constructing, repairing facilities, acquiring equipment; shall a measure authorizing $115,000,000 in bonds at legal rates, levying $30 per $100,000 of assessed valuation, ($6,200,000 annually) while bonds are outstanding, requiring citizens’ oversight, spending disclosure/audits, be adopted?",
     BASE + "measure-o-110326", ""),
    ("P", "County of Marin",
     "Shall the Marin County Child Care Initiative be adopted to levy a special parcel tax of 5 cents per building square foot, generating approximately $12.5 million annually for fifteen years, to fund affordable childcare and high-quality early childhood education and improve compensation to retain and attract educators, with public disclosure, optional annual inflation adjustments, and a corresponding increase in the County appropriations limit, with all funds used locally in Marin County?",
     BASE + "measure-p-110326", ""),
    ("Q", "Town of Corte Madera",
     "To maintain rapid 9-1-1 emergency response times and preserve the number of on-duty paramedics ready to respond to accidents/medical emergencies, shall the Ross Valley Paramedic Authority measure be adopted continuing for four years the paramedic services special tax of up to $94.50/residential living unit or 1,000 square feet of developed nonresidential property, adjusted up to $7.75/year, generating approximately $786,000 annually, with annual audits, public spending disclosure and all funds for local paramedic services?",
     BASE + "measure-q-110326", ""),
    ("R", "Town of Fairfax",
     "To maintain 9-1-1 emergency response times and the number of Ross Valley Paramedic Authority on-duty paramedics ready to respond to accidents/medical emergencies, shall the measure be adopted extending the Fairfax paramedic services special tax for four years at a rate of up to $107.50/residential living unit or 1,000 square feet of developed nonresidential property, adjusted by up to $4.00/year, generating approximately $432,000 annually, with annual audits; public spending disclosure; all funds for local paramedic services?",
     BASE + "measure-r-110326", ""),
    ("S", "City of Larkspur",
     "To maintain rapid 9-1-1 emergency response times and preserve the number of on-duty paramedics ready to respond to accidents/medical emergencies, shall the Ross Valley Paramedic Authority measure be adopted continuing for four years the paramedic services special tax of up to $107.50/residential living unit or 1,000 square feet of developed nonresidential property, adjusted up to $4.00/year, generating approximately $834,000 annually, with annual audits, public spending disclosure and all funds for local paramedic services?",
     BASE + "measure-s-110326", ""),
    ("T", "City of Mill Valley",
     "To renew funding exclusively for improved fire suppression activities including vegetation management and tree maintenance, and road repair and street maintenance, shall the Mill Valley Municipal Service Tax be renewed within the City of Mill Valley Community Facilities District Number 2026-1, at a rate of $303 for single family residential property, with a 2% annual adjustment, raising an average of $1.9 million annually over 10 years, and shall the appropriations limit be established, all as specified in Mill Valley City Council Resolution No. 26-49?",
     BASE + "measure-t-110326", ""),
    ("U", "Town of Ross",
     "To maintain local ambulance services staffed by paramedics available to respond to 9-1-1 emergencies, shall the Ross Valley Paramedic Authority measure be adopted continuing for four years the paramedic services special tax of up to $107.50/residential living unit or 1,000 square feet of developed nonresidential property, adjusted up to $4/year, generating approximately $111,000 annually, with annual audits, public spending disclosure and all funds for local paramedic services?",
     BASE + "measure-u-110326", ""),
    ("V", "Town of San Anselmo",
     "To maintain rapid 9-1-1 emergency response times and preserve the number of on-duty paramedics ready to respond to accidents/medical emergencies, shall the Ross Valley Paramedic Authority measure be adopted continuing for four years the paramedic services special tax of up to $107.50/residential living unit or 1,000 square feet of developed nonresidential property, adjusted up to $4/year, generating approximately $688,000 annually, with annual audits, public spending disclosure and all funds for local paramedic services?",
     BASE + "measure-v-110326", ""),
    ("W", "City of San Rafael",
     "San Rafael Essential Services Protection Measure. To provide locally controlled funding for essential city services, such as fire protection, paramedics, rapid 9-1-1 emergency response times; preventing street/road deterioration; addressing impacts of homelessness/litter/illegal dumping; and other services, shall the City of San Rafael’s measure be adopted increasing the current real property transfer tax rate from 0.2% to 1% (only paid upon sale), generating approximately $7,500,000 annually until ended by voters, with annual audits and public spending disclosure?",
     BASE + "measure-w-110326", ""),
    ("X", "City of Sausalito",
     'Shall the measure named the "Arts. Industrial & Maritime Preservation and Improvement Initiative," which revises zoning standards in the I and W zoning district to increase permitted height, building coverage limits and floor area ratio and allow certain new land uses; repeals the Marinship Specific Plan; revises Ordinance No. 1022 to allow future city council modifications to zoning outside the Downtown Historic District; and modifies various portions of the Sausalito General Plan, be adopted?',
     BASE + "measure-city-sausalito-110326", ""),
    ("Y", "County Services Area 27 – Ross Valley Paramedic Authority",
     "To maintain rapid 9-1-1 emergency response times and preserve the number of on-duty paramedics ready to respond to accidents/medical emergencies, shall the Ross Valley Paramedic Authority measure be adopted continuing for four years the paramedic services special tax of up to $107.50/residential living unit or 1,000 square feet of developed nonresidential property, adjusted up to $4/year, generating approximately $84,000 annually, with annual audits, public spending disclosure and all funds for local paramedic services?",
     BASE + "measure-csa-27-ross-valley-paramedic-service-area-110326", ""),
    ("Z", "County Services Area 29 – Paradise Cay",
     "For ongoing maintenance dredging in the principal waterways of Paradise Cay along with the north and south entry channels to San Francisco Bay, shall the measure for an annual parcel tax in County Service Area No. 29, for $2,200 per lot per year commencing in July 2027 providing an estimated $272,800 and automatically increasing 3% each year thereafter, for a total of ten years, be adopted?",
     BASE + "measure-csa-29-paradise-cay-service-area-110326", ""),
    ("AA", "Inverness Public Utility District",
     "Shall the measure adjusting the appropriations limit for the Inverness Public Utility District pursuant to Article XIIIB of the California Constitution so that for each of the fiscal years 2026/2027 through 2029/2030 the appropriations limit shall include the combined total of all applicable revenue sources be adopted?",
     BASE + "measure-inverness-public-utility-district-110326", ""),
    ("BB", "Kentfield Fire Protection District",
     "To maintain rapid 9-1-1 emergency response times and preserve the number of on-duty paramedics ready to respond to accidents/medical emergencies, shall the Ross Valley Paramedic Authority measure be adopted continuing for four years the paramedic services special tax of up to $107.50/residential living unit or 1,000 square feet of developed nonresidential property, adjusted up to $4/year, generating approximately $326,000 annually, with annual audits, public spending disclosure and all funds for local paramedic services?",
     BASE + "measure-kentfield-fire-protection-district-110326", ""),
    ("CC", "Marin Healthcare District",
     "Shall the measure funding expanded and upgraded emergency room, intensive care, hospital, and other medical facilities to care for trauma, heart attack, stroke, and other patients and attract qualified doctors and nurses, with no funds for administrator salaries, by enacting a parcel tax of 14¢ per square foot of improved building area annually, generating approximately $12,400,000 annually for 30 years, subject to annual audits and citizens' committee oversight, be adopted?",
     BASE + "measure-cc-110326", ""),
    ("DD", "Sleepy Hollow Fire Protection District",
     "To maintain rapid 9-1-1 emergency response times and preserve the number of on-duty paramedics ready to respond to accidents/medical emergencies, shall the Ross Valley Paramedic Authority measure be adopted continuing for four years the paramedic services special tax of up to $107.50/residential living unit or 1,000 square feet of developed nonresidential property, adjusted up to $4/year, generating approximately One Hundred Five Thousand Dollars ($105,000) annually, with annual audits, public spending disclosure and all funds for local paramedic services?",
     BASE + "measure-sleepy-hollow-fire-protection-district-110326", ""),
    ("EE", "Stinson Beach County Water District",
     "Shall the appropriations limit of the Stinson Beach County Water District for Fiscal Year 2026-2027 be established at $1,536,312 and should the limit for that Fiscal Year (i.e., $1,536,312) be used to determine the limits for Fiscal Years 2026-2027 through 2029-2030?",
     BASE + "measure-stinson-beach-county-water-district-110326", ""),
    ("FF", "Upper Bay Permanent Road Division",
     "Shall the measure be adopted authorizing a special tax on parcels within the Division of $4,350 per improved parcel and $2,175 per unimproved parcel per year for 10 years, beginning Fiscal Year 2027-28, totaling approximately $456,750, to fund improvements; thereafter, authorizing a special tax of $455 per parcel per year for ongoing maintenance, adjusted annually effective July 1 every year in accordance with the Consumer Price Index for All Urban Consumers San Francisco—Oakland—Hayward for the previous calendar year.",
     BASE + "measure-upper-bay-permanent-road-division110326", ""),
]
